name: Build and test library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 18.6.0
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Build library
        run: |
          yarn build
      - name: Test library
        run: |
          yarn test
