name: Build and test library

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup NodeJS
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 15.12.0
    - name: Install dependencies
      run: |
          npm ci
    - name: Build library
      run: |
          npm run build
    - name: Test library
      run: |
          npm run test
