name: Build and deploy example app on GitHub pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16.5.0
      - name: Build table-engine
        run: |
          yarn install --frozen-lockfile
          npm run build
      - name: Build demo app
        run: |
          cd example
          yarn install --frozen-lockfile
          npm run build -- --base-href=https://bennyboer.github.io/table-engine/
      - name: Deploy demo app to GitHub pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: example/dist/example
          token: ${{ secrets.GITHUBPAGESDEPLOYTOKEN }}
